<?php
global $DB;
$db_type = mb_strtolower($DB->type);
CModule::AddAutoloadClasses(
  'rns.integrations',
  [
    'RNS\Integrations\ExchangeTypeTable' => 'lib/'.$db_type.'/ExchangeTypeTable.php',
    'RNS\Integrations\ExternalSystemTable' => 'lib/'.$db_type.'/ExternalSystemTable.php',
    'RNS\Integrations\IntegrationOptionsTable' => 'lib/'.$db_type.'/IntegrationOptionsTable.php',
    'RNS\Integrations\Helpers\Column' => 'lib/helpers/Column.php',
    'RNS\Integrations\Helpers\TableHelper' => 'lib/'.$db_type.'/TableHelper.php',
    'RNS\Integrations\Helpers\UserFieldHelper' => 'lib/helpers/UserFieldHelper.php',
    'RNS\Integrations\Helpers\HLBlockHelper' => 'lib/helpers/HLBlockHelper.php',
    'RNS\Integrations\Helpers\EntityFacade' => 'lib/helpers/EntityFacade.php',
    'RNS\Integrations\Helpers\TaskHelper' => 'lib/helpers/TaskHelper.php',
    'RNS\Integrations\Helpers\ICS' => 'lib/helpers/ICS.php',
    'JsonMapper' => 'lib/helpers/JsonMapper.php',
    'RNS\Integrations\Models\OptionsBase' => 'lib/models/OptionsBase.php',
    'RNS\Integrations\Models\DatabaseOptions' => 'lib/models/DatabaseOptions.php',
    'RNS\Integrations\Models\FilesOptions' => 'lib/models/FilesOptions.php',
    'RNS\Integrations\Models\ApiOptions' => 'lib/models/ApiOptions.php',
    'RNS\Integrations\Models\EmailOptions' => 'lib/models/EmailOptions.php',
    'RNS\Integrations\Models\EntityTypeMapItem' => 'lib/models/EntityTypeMapItem.php',
    'RNS\Integrations\Models\EntityTypeMap' => 'lib/models/EntityTypeMap.php',
    'RNS\Integrations\Models\EntityStatusMapItem' => 'lib/models/EntityStatusMapItem.php',
    'RNS\Integrations\Models\EntityStatusMap' => 'lib/models/EntityStatusMap.php',
    'RNS\Integrations\Models\PropertyMapItem' => 'lib/models/PropertyMapItem.php',
    'RNS\Integrations\Models\PropertyMap' => 'lib/models/PropertyMap.php',
    'RNS\Integrations\Models\EntityMapItem' => 'lib/models/EntityMapItem.php',
    'RNS\Integrations\Models\EntityMap' => 'lib/models/EntityMap.php',
    'RNS\Integrations\Models\UserMapItem' => 'lib/models/UserMapItem.php',
    'RNS\Integrations\Models\UserMap' => 'lib/models/UserMap.php',
    'RNS\Integrations\Models\ResponsibleSettings' => 'lib/models/ResponsibleSettings.php',
    'RNS\Integrations\Models\Mapping' => 'lib/models/Mapping.php',
    'RNS\Integrations\Models\IntegrationOptionsTableWrapper' => 'lib/models/IntegrationOptionsTableWrapper.php',
    'RNS\Integrations\Models\IntegrationSettings' => 'lib/models/IntegrationSettings.php',
    'RNS\Integrations\Processors\FieldHandlerBase' => 'lib/processors/FieldHandlerBase.php',
    'RNS\Integrations\Processors\Hooks\jira\FieldHandler' => 'lib/processors/hooks/jira/FieldHandler.php',
    'RNS\Integrations\Processors\Database\Import' => 'lib/processors/database/Import.php',
    'RNS\Integrations\Processors\Files\FileValidationError' => 'lib/processors/files/FileValidationError.php',
    'RNS\Integrations\Processors\Files\Import' => 'lib/processors/files/Import.php',
    'RNS\Integrations\Processors\DataTransferResult' => 'lib/processors/DataTransferResult.php',
    'RNS\Integrations\Processors\DataTransferBase' => 'lib/processors/DataTransferBase.php',
    'RNS\Integrations\Processors\DataProviderBase' => 'lib/processors/DataProviderBase.php',
    'RNS\Integrations\Processors\IntegrationAgent' => 'lib/processors/IntegrationAgent.php',
    'RNS\Integrations\Controller\ControllerBase' => 'lib/controller/ControllerBase.php',
    'RNS\Integrations\Helpers\ImportHelper' => 'lib/helpers/ImportHelper.php',
    'RNS\Integrations\Controller\Entity' => 'lib/controller/Entity.php',
    'RNS\Integrations\Controller\Task' => 'lib/controller/Task.php',
    'RNS\Integrations\Controller\User' => 'lib/controller/User.php',
    'RNS\Integrations\Controller\Hlb' => 'lib/controller/Hlb.php',
    'RNS\Integrations\Controller\Project' => 'lib/controller/Project.php',
    'RNS\Integrations\Handlers\Epilog' => 'lib/handlers/Epilog.php',
    'RNS\Integrations\Migrations\HelperInstaller' => 'lib/migrations/HelperInstaller.php',
  ]
);
